/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as LeaderboardGroupIdRouteImport } from './routes/leaderboard.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardGroupIdRoute = LeaderboardGroupIdRouteImport.update({
  id: '/leaderboard/$groupId',
  path: '/leaderboard/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches': typeof MatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboard/$groupId' | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboard/$groupId' | '/matches'
  id: '__root__' | '/' | '/leaderboard/$groupId' | '/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardGroupIdRoute: typeof LeaderboardGroupIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$groupId': {
      id: '/leaderboard/$groupId'
      path: '/leaderboard/$groupId'
      fullPath: '/leaderboard/$groupId'
      preLoaderRoute: typeof LeaderboardGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardGroupIdRoute: LeaderboardGroupIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
