/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as LeaderboardGroupIdRouteImport } from './routes/leaderboard.$groupId'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups/$groupId/members'
import { Route as GroupsGroupIdInviteRouteImport } from './routes/groups/$groupId/invite'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardGroupIdRoute = LeaderboardGroupIdRouteImport.update({
  id: '/leaderboard/$groupId',
  path: '/leaderboard/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/groups/$groupId/members',
  path: '/groups/$groupId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdInviteRoute = GroupsGroupIdInviteRouteImport.update({
  id: '/groups/$groupId/invite',
  path: '/groups/$groupId/invite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/groups/$groupId/invite': typeof GroupsGroupIdInviteRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/groups': typeof GroupsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/groups/$groupId/invite': typeof GroupsGroupIdInviteRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/leaderboard/$groupId': typeof LeaderboardGroupIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/groups/$groupId/invite': typeof GroupsGroupIdInviteRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/today'
    | '/groups/new'
    | '/invite/$token'
    | '/leaderboard/$groupId'
    | '/matches/$matchId'
    | '/groups/'
    | '/matches/'
    | '/groups/$groupId/invite'
    | '/groups/$groupId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/today'
    | '/groups/new'
    | '/invite/$token'
    | '/leaderboard/$groupId'
    | '/matches/$matchId'
    | '/groups'
    | '/matches'
    | '/groups/$groupId/invite'
    | '/groups/$groupId/members'
  id:
    | '__root__'
    | '/'
    | '/today'
    | '/groups/new'
    | '/invite/$token'
    | '/leaderboard/$groupId'
    | '/matches/$matchId'
    | '/groups/'
    | '/matches/'
    | '/groups/$groupId/invite'
    | '/groups/$groupId/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodayRoute: typeof TodayRoute
  GroupsNewRoute: typeof GroupsNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LeaderboardGroupIdRoute: typeof LeaderboardGroupIdRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  GroupsGroupIdInviteRoute: typeof GroupsGroupIdInviteRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$groupId': {
      id: '/leaderboard/$groupId'
      path: '/leaderboard/$groupId'
      fullPath: '/leaderboard/$groupId'
      preLoaderRoute: typeof LeaderboardGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members': {
      id: '/groups/$groupId/members'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/invite': {
      id: '/groups/$groupId/invite'
      path: '/groups/$groupId/invite'
      fullPath: '/groups/$groupId/invite'
      preLoaderRoute: typeof GroupsGroupIdInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodayRoute: TodayRoute,
  GroupsNewRoute: GroupsNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  LeaderboardGroupIdRoute: LeaderboardGroupIdRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  GroupsGroupIdInviteRoute: GroupsGroupIdInviteRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
